"""create_magic_link_tokens_table

Revision ID: 09cdf7b28711
Revises: f94cdb937096
Create Date: 2026-08-16 16:14:48.260237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09cdf7b28711'
down_revision: Union[str, Sequence[str], None] = 'f94cdb937096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_code_hash'), 'magic_link_tokens', ['code_hash'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_id'), 'magic_link_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token_hash'), 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_magic_link_tokens_used'), 'magic_link_tokens', ['used'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_user_id'), 'magic_link_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_doctors_fulltext'), table_name='doctors', postgresql_using='gin')
    op.drop_index(op.f('ix_product_fulltext'), table_name='product', postgresql_using='gin')
    op.drop_index(op.f('ix_user_magic_link_token'), table_name='user')
    op.drop_column('user', 'magic_link_token')
    op.drop_column('user', 'magic_link_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('magic_link_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('magic_link_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_magic_link_token'), 'user', ['magic_link_token'], unique=False)
    op.create_index(op.f('ix_product_fulltext'), 'product', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_doctors_fulltext'), 'doctors', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(specialization, ''::character varying)::text || ' '::text) || COALESCE(qualification, ''::character varying)::text) || ' '::text) || COALESCE(bio, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_magic_link_tokens_user_id'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_used'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_token_hash'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_id'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_code_hash'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    # ### end Alembic commands ###
