"""create_health_records_table

Revision ID: 95d5e3236013
Revises: 8f01d37b283c
Create Date: 2026-08-14 09:54:11.870108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d5e3236013'
down_revision: Union[str, Sequence[str], None] = '8f01d37b283c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.Enum('general', 'symptom', 'diagnosis', 'treatment', 'vaccination', 'medication', 'lab_result', 'surgery', 'allergy', 'follow_up', name='health_record_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('clinical_findings', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_consultation_id'), 'health_records', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_health_records_created_at'), 'health_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_health_records_doctor_id'), 'health_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_health_records_id'), 'health_records', ['id'], unique=False)
    op.create_index(op.f('ix_health_records_pet_id'), 'health_records', ['pet_id'], unique=False)
    op.create_index(op.f('ix_health_records_record_type'), 'health_records', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_records_record_type'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_pet_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_doctor_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_created_at'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_consultation_id'), table_name='health_records')
    op.drop_table('health_records')
    # ### end Alembic commands ###
