"""add_magic_link_and_oauth_fields

Revision ID: f94cdb937096
Revises: d4b3609ee3c8
Create Date: 2026-08-15 23:34:12.417257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94cdb937096'
down_revision: Union[str, Sequence[str], None] = 'd4b3609ee3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('user', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('auth_provider', sa.String(length=50), nullable=False, server_default='magic_link'))
    op.add_column('user', sa.Column('oauth_sub', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('magic_link_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('magic_link_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_user_magic_link_token'), 'user', ['magic_link_token'], unique=False)
    op.create_index(op.f('ix_user_oauth_sub'), 'user', ['oauth_sub'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_sub'), table_name='user')
    op.drop_index(op.f('ix_user_magic_link_token'), table_name='user')
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'magic_link_expires_at')
    op.drop_column('user', 'magic_link_token')
    op.drop_column('user', 'is_email_verified')
    op.drop_column('user', 'oauth_sub')
    op.drop_column('user', 'auth_provider')
    op.drop_column('user', 'profile_image_url')
    op.create_index(op.f('ix_product_fulltext'), 'product', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_doctors_fulltext'), 'doctors', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(specialization, ''::character varying)::text || ' '::text) || COALESCE(qualification, ''::character varying)::text) || ' '::text) || COALESCE(bio, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
