import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FAF7F2' },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#FAF7F2',
  },
  headerLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  headerTextCol: { flex: 1, minWidth: 0 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.brandGold,
    letterSpacing: 0.8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.textCoffee,
    marginTop: 2,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#C3E6CB',
  },
  onlineDot: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#2E7D32' },
  liveBadgeText: { fontSize: 11, fontWeight: '700', color: COLORS.forestGreen },

  // Top Segmented Switcher
  segmentContainer: {
    flexDirection: 'row',
    padding: 12,
    gap: 10,
    backgroundColor: '#FAF7F2',
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    backgroundColor: COLORS.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentBtnActive: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  segmentBtnInner: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  segmentBtnText: { fontSize: 12, fontWeight: '700', color: COLORS.textCoffee },
  segmentBtnTextActive: { color: '#FFFFFF' },

  scrollBody: { padding: 16, paddingBottom: 40, gap: 14 },
  headerAreaContainer: { paddingHorizontal: 16, paddingTop: 14 },

  // Filter Chips
  filterChipRow: { flexDirection: 'row', gap: 8, marginBottom: 4, paddingRight: 16 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  filterChipActive: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  // Cancelled gets its own active tone (matching the CANCELLED status badge's
  // red, not the generic forest-green every other active filter chip uses).
  filterChipCancelledActive: {
    backgroundColor: '#DC2626',
    borderColor: '#DC2626',
  },
  filterChipText: { fontSize: 11, fontWeight: '700', color: COLORS.textCoffee },
  filterChipTextActive: { color: '#FFFFFF' },

  // Consultations Cards
  consultationsGridRow: { gap: 14 },
  consultationCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 12,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardIdBadge: {
    backgroundColor: '#FAF5EE',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  cardIdText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.brandGold,
    letterSpacing: 0.5,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  livePulseDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#2E7D32' },
  statusBadgeText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.5 },

  doctorInfoRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  doctorAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  doctorAvatarFallback: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#EDF5F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C3E6CB',
  },
  doctorTextCol: { flex: 1, gap: 2 },
  doctorName: { fontSize: 15, fontWeight: '800', color: COLORS.textCoffee },
  doctorSpec: { fontSize: 12, fontWeight: '600', color: COLORS.brandGold },
  clinicRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  clinicText: { fontSize: 11, color: COLORS.textMuted },

  cardDivider: { height: 1, backgroundColor: COLORS.kraftBorder },

  detailsGrid: { flexDirection: 'row', justifyContent: 'space-between' },
  detailItem: { gap: 2, flex: 1 },
  detailLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.5,
  },
  detailValueRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  detailValueText: { fontSize: 12, fontWeight: '700', color: COLORS.textCoffee },

  reasonBox: {
    backgroundColor: '#FAF9F6',
    padding: 10,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.brandGold,
    gap: 2,
  },
  reasonLabel: { fontSize: 9, fontWeight: '800', color: COLORS.textMuted },
  reasonText: { fontSize: 12, fontStyle: 'italic', color: COLORS.textCoffee },

  doctorNotesBox: {
    backgroundColor: '#EDF5F0',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#C3E6CB',
    gap: 6,
  },
  notesHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  notesHeaderTitle: { fontSize: 12, fontWeight: '800', color: COLORS.forestGreen },
  doctorNotesText: { fontSize: 12, color: COLORS.textCoffee, lineHeight: 17 },

  cardActionRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginTop: 2,
  },
  joinCallBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 12,
    borderRadius: 12,
  },
  joinCallBtnText: { fontSize: 13, fontWeight: '800', color: '#FFFFFF' },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
  },
  cancelBtnText: { fontSize: 11, fontWeight: '700', color: '#DC2626' },
  completedStamp: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  completedStampText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.forestGreen,
  },
  btnDisabled: { opacity: 0.5 },
  leaveReviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    backgroundColor: COLORS.card,
  },
  leaveReviewBtnText: { fontSize: 11, fontWeight: '700', color: COLORS.textCoffee },

  // Empty & Loading States
  loadingBox: { padding: 40, alignItems: 'center', gap: 12 },
  loadingText: { fontSize: 13, color: COLORS.textMuted },
  emptyContainer: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 10,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FAF5EE',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  emptyTitle: { fontSize: 16, fontWeight: '800', color: COLORS.textCoffee },
  emptySub: {
    fontSize: 12,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
  bookNowBtn: {
    marginTop: 6,
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  bookNowBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 12 },

  // Tab 2: Doctors List
  doctorGridRow: { gap: 14 },
  docCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 10,
  },
  docCardTop: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  docImg: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  docImgFallback: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#EDF5F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C3E6CB',
  },
  verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  docCardName: { fontSize: 16, fontWeight: '800', color: COLORS.textCoffee },
  docCardSpec: { fontSize: 12, fontWeight: '700', color: COLORS.brandGold },
  docCardQual: { fontSize: 11, color: COLORS.textMuted },
  docCardExp: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.forestGreen,
    marginTop: 2,
  },
  docBio: { fontSize: 11, color: COLORS.textMuted, lineHeight: 16 },
  docCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  feeLabel: { fontSize: 9, fontWeight: '800', color: COLORS.textMuted },
  feeVal: { fontSize: 18, fontWeight: '900', color: COLORS.forestGreen },
  bookDocBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  bookDocBtnDisabled: {
    backgroundColor: '#9CA3AF',
    opacity: 0.7,
  },
  bookDocBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 12 },

  // ==========================================================
  // Interactive Modal Styles
  // ==========================================================
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '92%',
    padding: 20,
    gap: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalSubHeader: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.brandGold,
    letterSpacing: 0.8,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textCoffee },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: { gap: 14, paddingBottom: 24 },

  reviewModalSheet: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 16,
  },
  reviewModalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewModalTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textCoffee },
  reviewModalSubtitle: { fontSize: 13, color: COLORS.textMuted },
  reviewStarRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  reviewStarBtn: { padding: 4 },
  reviewCommentInput: {
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    color: COLORS.textCoffee,
    minHeight: 90,
    backgroundColor: COLORS.canvas,
  },
  reviewSubmitBtn: {
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewSubmitBtnText: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },

  modalDoctorBrief: {
    flexDirection: 'row',
    gap: 12,
    backgroundColor: '#FAF5EE',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  modalDocAvatarImg: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  docBriefAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EDF5F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDocName: { fontSize: 14, fontWeight: '800', color: COLORS.textCoffee },
  modalDocSpec: { fontSize: 11, color: COLORS.brandGold, fontWeight: '600' },
  modalDocFee: { fontSize: 11, color: COLORS.forestGreen, fontWeight: '700' },

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  modalFieldLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textCoffee,
    letterSpacing: 0.5,
  },
  requiredBadge: {
    fontSize: 9,
    fontWeight: '800',
    color: COLORS.brandGold,
    backgroundColor: '#FAF5EE',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  subDateHint: { fontSize: 11, fontWeight: '700', color: COLORS.forestGreen },

  // Pet Selector
  noPetsWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEF3C7',
    padding: 10,
    borderRadius: 8,
  },
  noPetsText: { fontSize: 11, color: '#92400E', flex: 1 },
  petsScroll: { flexDirection: 'row' },
  petCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.canvas,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    marginRight: 8,
  },
  petCardSelected: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  petAvatarImg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  petAvatarBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FAF5EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  petAvatarBoxSelected: { backgroundColor: '#2E7D32' },
  petNameText: { fontSize: 13, fontWeight: '800', color: COLORS.textCoffee },
  petNameTextSelected: { color: '#FFFFFF' },
  petBreedText: { fontSize: 10, color: COLORS.textMuted },
  petBreedTextSelected: { color: '#E5E7EB' },

  // 14-Day Calendar Strip
  calendarStrip: { flexDirection: 'row', paddingVertical: 4 },
  dateItem: {
    width: 60,
    height: 74,
    borderRadius: 14,
    backgroundColor: COLORS.canvas,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    gap: 2,
  },
  dateItemSelected: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  dateDayName: { fontSize: 9, fontWeight: '800', color: COLORS.textMuted },
  dateDayNameSelected: { color: '#E5E7EB' },
  dateNumber: { fontSize: 17, fontWeight: '900', color: COLORS.textCoffee },
  dateNumberSelected: { color: '#FFFFFF' },
  dateMonth: { fontSize: 9, fontWeight: '800', color: COLORS.brandGold },
  dateMonthSelected: { color: '#FFDD43' },
  dateDotActive: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FFDD43',
    marginTop: 1,
  },
  dateItemOffDuty: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
    opacity: 0.65,
  },
  dateDayNameOffDuty: {
    color: '#9CA3AF',
  },
  dateNumberOffDuty: {
    color: '#9CA3AF',
  },
  dateMonthOffDuty: {
    color: '#9CA3AF',
  },
  dateDotWorking: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.forestGreen,
    marginTop: 1,
  },
  dateOffBadge: {
    fontSize: 7,
    fontWeight: '800',
    color: '#9CA3AF',
    marginTop: 1,
  },
  scheduleSummaryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FAF5EE',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    marginBottom: 8,
  },
  scheduleSummaryText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textCoffee,
    flex: 1,
  },

  // Time Slots
  selectedTimeBadge: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.forestGreen,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  slotLoadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.canvas,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  slotLoadingText: { fontSize: 12, color: COLORS.textMuted },
  noDoctorSlotsCard: {
    alignItems: 'center',
    backgroundColor: '#FAF5EE',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 6,
    marginVertical: 4,
  },
  noDoctorSlotsTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textCoffee,
  },
  noDoctorSlotsSub: {
    fontSize: 11,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 16,
  },
  slotsSourceNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#EDF5F0',
    padding: 6,
    borderRadius: 6,
  },
  slotsSourceText: { fontSize: 10, color: COLORS.forestGreen, fontWeight: '600' },

  // Slot Groups by Time of Day
  slotPeriodGroup: { gap: 6, marginTop: 4 },
  slotPeriodHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  slotPeriodTitle: { fontSize: 11, fontWeight: '800', color: COLORS.textCoffee },
  slotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timeSlotChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: COLORS.canvas,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    minWidth: '22%',
    justifyContent: 'center',
  },
  timeSlotChipSelected: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  timeSlotChipDisabled: {
    opacity: 0.35,
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  timeSlotText: { fontSize: 11, fontWeight: '700', color: COLORS.textCoffee },
  timeSlotTextSelected: { color: '#FFFFFF' },
  timeSlotTextDisabled: { color: '#9CA3AF' },

  // Quick Symptoms
  quickSymptomsScroll: { flexDirection: 'row', marginVertical: 4 },
  quickSymptomChip: {
    backgroundColor: '#FAF5EE',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    marginRight: 6,
  },
  quickSymptomText: { fontSize: 11, fontWeight: '600', color: COLORS.textCoffee },

  reasonInput: {
    backgroundColor: COLORS.canvas,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    color: COLORS.textCoffee,
    textAlignVertical: 'top',
    minHeight: 70,
  },

  // Summary Card
  appointmentSummaryCard: {
    backgroundColor: '#FAF9F6',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: { fontSize: 10, fontWeight: '800', color: COLORS.textMuted },
  summaryValue: { fontSize: 12, fontWeight: '800', color: COLORS.textCoffee },
  summaryFee: { fontSize: 16, fontWeight: '900', color: COLORS.forestGreen },

  confirmBookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 15,
    borderRadius: 14,
    marginTop: 4,
  },
  confirmBookBtnText: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },

  // ==========================================================
  // Doctor Profile Modal & Card Action Styles
  // ==========================================================
  docCardStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 3,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  ratingBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#92400E',
  },
  docCardActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  viewProfileOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EDF5F0',
    borderWidth: 1,
    borderColor: '#C3E6CB',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  viewProfileOutlineBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },

  profileModalSheet: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '92%',
    minHeight: '65%',
    paddingTop: 16,
  },
  profileHeaderBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  profileLoadingBox: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  profileContentScroll: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  profileHeroCard: {
    alignItems: 'center',
    backgroundColor: '#FAF5EE',
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    marginBottom: 16,
  },
  profileHeroImg: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 3,
    borderColor: COLORS.forestGreen,
    marginBottom: 12,
  },
  profileHeroImgFallback: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#EDF5F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#C3E6CB',
    marginBottom: 12,
  },
  profileHeroName: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.textCoffee,
    textAlign: 'center',
  },
  profileHeroSpec: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.brandGold,
    marginTop: 2,
    textAlign: 'center',
  },
  profilePillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
  },
  profileHighlightPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  profileHighlightPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textCoffee,
  },
  profileSection: {
    marginBottom: 16,
  },
  profileSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  profileBioText: {
    fontSize: 13,
    lineHeight: 20,
    color: COLORS.textCoffee,
    backgroundColor: COLORS.canvas,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  profileInfoBox: {
    backgroundColor: COLORS.canvas,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  profileInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileInfoLabel: {
    fontSize: 10,
    color: COLORS.textMuted,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  profileInfoValue: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textCoffee,
    marginTop: 1,
  },
  profileInfoDivider: {
    height: 1,
    backgroundColor: COLORS.kraftBorder,
    marginVertical: 10,
  },
  profileScheduleBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#EDF5F0',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#C3E6CB',
  },
  profileScheduleTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },
  profileScheduleSub: {
    fontSize: 12,
    color: COLORS.textCoffee,
    fontWeight: '600',
    marginTop: 2,
  },
  reviewsCountBadge: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },
  noReviewsBox: {
    padding: 16,
    backgroundColor: COLORS.canvas,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  noReviewsText: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  reviewCard: {
    backgroundColor: COLORS.canvas,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    marginBottom: 8,
  },
  reviewCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reviewerAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#2E7D32',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewerAvatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  reviewerName: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.textCoffee,
  },
  reviewDate: {
    fontSize: 9,
    color: COLORS.textMuted,
  },
  reviewStarsRow: {
    flexDirection: 'row',
    gap: 2,
  },
  reviewComment: {
    fontSize: 12,
    color: COLORS.textCoffee,
    marginTop: 6,
    lineHeight: 17,
  },
  profileBottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: COLORS.kraftBorder,
    backgroundColor: COLORS.card,
  },
  profileBookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
  },
  profileBookBtnText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 13,
  },

  // Search & Dynamic Live Filters
  searchSection: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 4,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 46,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textCoffee,
    paddingVertical: 0,
  },
  searchClearBtn: {
    padding: 6,
    borderRadius: 12,
    backgroundColor: COLORS.canvas,
  },
  filterTriggerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    height: 46,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  filterTriggerBtnActive: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  filterTriggerBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },
  filterTriggerBtnTextActive: {
    color: '#FFFFFF',
  },
  filterBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  filterBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    color: COLORS.forestGreen,
  },

  dropdownTriggersStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 10,
    paddingBottom: 4,
  },
  dropdownTriggerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    maxWidth: 200,
  },
  dropdownTriggerPillActive: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  dropdownTriggerPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textCoffee,
  },
  dropdownTriggerPillTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  feeSymbol: {
    fontSize: 12,
    fontWeight: '900',
    color: COLORS.forestGreen,
  },

  activeFiltersRow: {
    paddingTop: 8,
  },
  activeChipsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activeFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EDF5F0',
    borderWidth: 1,
    borderColor: '#C3E6CB',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  activeFilterChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },
  clearAllFiltersBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  clearAllFiltersText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.brandGold,
    textDecorationLine: 'underline',
  },

  searchSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingBottom: 6,
    paddingHorizontal: 2,
  },
  searchSummaryText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 0.3,
  },
  resetFiltersText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.brandGold,
    textDecorationLine: 'underline',
  },
  emptySearchIconBox: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FED7AA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  resetSearchBtn: {
    marginTop: 14,
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  resetSearchBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },

  // Dynamic Filter Modal Bottom Sheet
  filterModalSheet: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '88%',
    minHeight: '60%',
    paddingTop: 16,
  },
  filterResetModalText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.brandGold,
    paddingHorizontal: 6,
  },
  filterSegmentBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.kraftBorder,
    gap: 8,
  },
  filterSegmentTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: COLORS.canvas,
  },
  filterSegmentTabActive: {
    backgroundColor: '#EDF5F0',
    borderWidth: 1,
    borderColor: '#C3E6CB',
  },
  filterSegmentTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMuted,
  },
  filterSegmentTabTextActive: {
    color: COLORS.forestGreen,
    fontWeight: '800',
  },
  filterSegmentDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.forestGreen,
  },
  filterSegmentPriceSymbol: {
    fontSize: 13,
    fontWeight: '900',
    color: COLORS.textMuted,
  },

  filterModalScroll: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  filterSectionBlock: {
    marginBottom: 8,
  },
  filterSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textCoffee,
    letterSpacing: 0.8,
  },
  filterSectionCountBadge: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.forestGreen,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  filterSectionHint: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 4,
    marginBottom: 12,
  },
  filterSectionDivider: {
    height: 1,
    backgroundColor: COLORS.kraftBorder,
    marginVertical: 16,
  },
  filterPillsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChoicePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.canvas,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 14,
  },
  filterChoicePillActive: {
    backgroundColor: COLORS.forestGreen,
    borderColor: COLORS.forestGreen,
  },
  filterChoicePillText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textCoffee,
  },
  filterChoicePillTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  filterCurrentLimitBadge: {
    fontSize: 11,
    fontWeight: '900',
    color: COLORS.forestGreen,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },

  filterModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: COLORS.kraftBorder,
    backgroundColor: COLORS.card,
  },
  filterFooterCountText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textCoffee,
    marginTop: 2,
  },
  filterApplyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
  },
  filterApplyBtnText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 13,
  },
});

