import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../theme/colors';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FAF7F2' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#FAF7F2',
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.brandGold,
    letterSpacing: 1,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  syncPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  syncPillText: {
    fontSize: 9,
    color: COLORS.forestGreen,
    fontWeight: '700',
  },
  headerTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textCoffee },
  clearBtn: { padding: 6 },
  scrollBody: { padding: 20, gap: 16, paddingBottom: 40 },

  /* 3-Step Checkout Stepper Styles */
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.card,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.kraftBorder,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 18,
  },
  stepItemActive: {
    backgroundColor: '#EDF5F0',
  },
  stepCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircleActive: {
    backgroundColor: COLORS.forestGreen,
  },
  stepCircleCompleted: {
    backgroundColor: COLORS.forestGreen,
  },
  stepCircleInactive: {
    backgroundColor: '#FAF4EB',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textLight,
  },
  stepLabelActive: {
    color: COLORS.forestGreen,
    fontWeight: '800',
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: COLORS.kraftBorder,
    marginHorizontal: 4,
  },
  stepLineActive: {
    backgroundColor: COLORS.forestGreen,
  },

  /* Step Navigation & Action Bar Styles */
  stepBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  stepBackText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.forestGreen,
  },
  stepActionCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    marginTop: 4,
    shadowColor: COLORS.textCoffee,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  stepActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepActionSub: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  stepActionTotal: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.textCoffee,
  },
  stepActionAddressSnippet: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textCoffee,
    marginTop: 2,
  },
  primaryStepBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: 14,
    shadowColor: COLORS.forestGreen,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  primaryStepBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  /* Delivery Destination Summary Card (Step 3) */
  summaryAddressCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 8,
  },
  summaryAddressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryAddressTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textCoffee,
  },
  summaryEditBtn: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.forestGreen,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#EDF5F0',
  },
  summaryAddressBody: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textCoffee,
    lineHeight: 18,
  },
  summaryPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  summaryPhoneText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMuted,
  },
  phoneVerifiedMini: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  phoneVerifiedMiniText: {
    fontSize: 9,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },

  guestNoticeCard: {
    marginHorizontal: 20,
    marginTop: 12,
    backgroundColor: '#FAF4EB',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  guestNoticeRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  guestNoticeTitle: { fontSize: 12, fontWeight: '800', color: COLORS.textCoffee },
  guestNoticeSub: { fontSize: 10, color: COLORS.textMuted, marginTop: 2, lineHeight: 14 },
  guestSignInBtn: {
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  guestSignInBtnText: { fontSize: 11, fontWeight: '800', color: '#FFFFFF' },

  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
    gap: 14,
  },
  emptyIconBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FAF4EB',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.brandGold,
  },
  emptyTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textCoffee },
  emptySub: { fontSize: 13, color: COLORS.textMuted, textAlign: 'center', lineHeight: 19 },
  exploreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 6,
  },
  exploreBtnText: { fontSize: 13, fontWeight: '800', color: '#FFFFFF' },

  coldChainBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#EDF5F0',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#C3E6CB',
  },
  coldChainTitle: { fontSize: 12, fontWeight: '800', color: COLORS.forestGreen },
  coldChainSub: { fontSize: 10, color: COLORS.textMuted, marginTop: 2, lineHeight: 14 },

  itemList: { gap: 12 },
  cartCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  itemImage: { width: 64, height: 64, borderRadius: 12 },
  itemName: { fontSize: 14, fontWeight: '800', color: COLORS.textCoffee },
  portionBadge: {
    backgroundColor: '#FAF4EB',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  portionText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.brandGold,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  itemPrice: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textCoffee,
    marginTop: 2,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  unitPriceMuted: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  stepperWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.canvas,
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
  },
  stepperBtn: { padding: 5 },
  stepperQty: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textCoffee,
    minWidth: 18,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  deleteItemBtn: { padding: 6 },

  couponCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 8,
  },
  couponHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  couponHeading: { fontSize: 12, fontWeight: '800', color: COLORS.textCoffee },
  couponInputRow: { flexDirection: 'row', gap: 8 },
  couponInput: {
    flex: 1,
    backgroundColor: COLORS.canvas,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    color: COLORS.textCoffee,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: '700',
  },
  applyCouponBtn: {
    backgroundColor: COLORS.forestGreen,
    borderRadius: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyCouponBtnDisabled: {
    backgroundColor: '#8FA89B',
    opacity: 0.6,
  },
  applyCouponBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  appliedCouponCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F3F7F4',
    borderWidth: 1,
    borderColor: '#8FA89B',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  appliedCouponLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  appliedCheckCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.forestGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appliedCodeText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.forestGreen,
    letterSpacing: 0.5,
  },
  appliedBadge: {
    backgroundColor: '#E2EEE5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  appliedBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },
  appliedSavingsText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textLight,
    marginTop: 2,
  },
  removeCouponBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  removeCouponBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#C0392B',
  },
  couponErrorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    backgroundColor: '#FDF2F2',
    borderWidth: 1,
    borderColor: '#F8B4B4',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  couponErrorText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#C0392B',
    flex: 1,
  },

  sectionCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 10,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sectionHeading: { fontSize: 13, fontWeight: '800', color: COLORS.textCoffee },
  sectionSubtext: { fontSize: 11, color: COLORS.textMuted, marginTop: -4 },

  fieldGroup: { gap: 4 },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textCoffee,
  },
  inputField: {
    backgroundColor: COLORS.canvas,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 12,
    color: COLORS.textCoffee,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },

  phoneVerifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#EDF5F0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 'auto',
  },
  phoneVerifiedText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.forestGreen,
  },
  phoneUnverifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FAF4EB',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 'auto',
  },
  phoneUnverifiedText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.brandGold,
  },

  phoneRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  countryCodeBox: {
    backgroundColor: COLORS.canvas,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countryCodeText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.textCoffee,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  phoneInputFlex: {
    flex: 1,
    backgroundColor: COLORS.canvas,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: COLORS.textCoffee,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  verifyPhoneBtn: {
    backgroundColor: COLORS.brandGold,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifyPhoneBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  deliveryScheduleBox: {
    backgroundColor: '#FAF4EB',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 6,
  },
  scheduleBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scheduleBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.forestGreen,
  },
  scheduleDetailsText: {
    fontSize: 11,
    color: COLORS.textMuted,
    lineHeight: 16,
  },

  billCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 10,
  },
  billHeading: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textCoffee,
  },
  billRow: { flexDirection: 'row', justifyContent: 'space-between' },
  billLabel: { fontSize: 12, color: COLORS.textMuted },
  billVal: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textCoffee,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: COLORS.kraftBorder,
    paddingTop: 10,
    marginTop: 4,
  },
  totalLabel: { fontSize: 14, fontWeight: '800', color: COLORS.textCoffee },
  totalVal: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.forestGreen,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },

  checkoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: COLORS.forestGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  checkoutBtnText: { fontSize: 15, fontWeight: '800', color: '#FFFFFF' },
  securityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 4,
  },
  securityText: { fontSize: 11, color: COLORS.textMuted },

  /* Success Screen */
  successContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 14,
  },
  successIconCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#EDF5F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#C3E6CB',
  },
  successBadge: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.brandGold,
    letterSpacing: 1,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  successTitle: { fontSize: 22, fontWeight: '800', color: COLORS.textCoffee },
  successSub: {
    fontSize: 13,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 19,
  },
  dispatchCard: {
    width: '100%',
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    gap: 10,
    marginTop: 8,
  },
  dispatchRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  dispatchText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textCoffee,
    flex: 1,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  successBtnRow: {
    width: '100%',
    gap: 10,
    marginTop: 12,
  },
  viewOrderHistoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 14,
    borderRadius: 14,
  },
  viewOrderHistoryText: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
  backToMenuBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FAF4EB',
    borderWidth: 1,
    borderColor: COLORS.kraftBorder,
    paddingVertical: 14,
    borderRadius: 14,
  },
  backToMenuText: { fontSize: 14, fontWeight: '700', color: COLORS.forestGreen },

  /* Payment Failure & Recovery Styles */
  paymentRecoveryCard: {
    backgroundColor: '#FFF8F6',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#F8D2CC',
    marginBottom: 16,
    gap: 12,
  },
  paymentRecoveryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  paymentRecoveryTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.accentRed,
  },
  paymentRecoverySub: {
    fontSize: 12,
    color: COLORS.textCoffee,
    marginTop: 2,
    lineHeight: 17,
  },
  prepaidNoticeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#F3EFE9',
    padding: 10,
    borderRadius: 10,
  },
  prepaidNoticeText: {
    flex: 1,
    fontSize: 11,
    color: COLORS.textMuted,
    lineHeight: 15,
  },
  retryPaymentBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.forestGreen,
    paddingVertical: 13,
    borderRadius: 12,
    shadowColor: COLORS.forestGreen,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  retryPaymentBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});
