"""ImageNet-1K class definitions with specialized Dog and Cat pet mappings."""

from typing import Dict, Tuple

# Maps ImageNet class index (0-999) -> (Species, Display Breed, Metadata Slug)
# 151 to 268: 118 Dog breeds
# 281 to 285: Cat breeds
PET_CLASSES: Dict[int, Tuple[str, str, str]] = {
    # ------------------ DOGS (151 - 268) ------------------
    151: ("Dog", "Chihuahua", "chihuahua"),
    152: ("Dog", "Japanese Spaniel", "japanese_spaniel"),
    153: ("Dog", "Maltese Dog", "maltese"),
    154: ("Dog", "Pekingese", "pekingese"),
    155: ("Dog", "Shih Tzu", "shih_tzu"),
    156: ("Dog", "Blenheim Spaniel", "cocker_spaniel"),
    157: ("Dog", "Papillon", "papillon"),
    158: ("Dog", "Toy Terrier", "toy_terrier"),
    159: ("Dog", "Rhodesian Ridgeback", "rhodesian_ridgeback"),
    160: ("Dog", "Afghan Hound", "afghan_hound"),
    161: ("Dog", "Basset Hound", "basset_hound"),
    162: ("Dog", "Beagle", "beagle"),
    163: ("Dog", "Bloodhound", "bloodhound"),
    164: ("Dog", "Bluetick Coonhound", "bluetick"),
    165: ("Dog", "Black-and-Tan Coonhound", "coonhound"),
    166: ("Dog", "Walker Hound", "walker_hound"),
    167: ("Dog", "English Foxhound", "foxhound"),
    168: ("Dog", "Redbone Coonhound", "redbone"),
    169: ("Dog", "Borzoi", "borzoi"),
    170: ("Dog", "Irish Wolfhound", "irish_wolfhound"),
    171: ("Dog", "Italian Greyhound", "italian_greyhound"),
    172: ("Dog", "Whippet", "whippet"),
    173: ("Dog", "Ibizan Hound", "ibizan_hound"),
    174: ("Dog", "Norwegian Elkhound", "elkhound"),
    175: ("Dog", "Otterhound", "otterhound"),
    176: ("Dog", "Saluki", "saluki"),
    177: ("Dog", "Scottish Deerhound", "deerhound"),
    178: ("Dog", "Weimaraner", "weimaraner"),
    179: ("Dog", "Staffordshire Bull Terrier", "staffordshire"),
    180: ("Dog", "American Staffordshire Terrier", "amstaff"),
    181: ("Dog", "Bedlington Terrier", "bedlington"),
    182: ("Dog", "Border Terrier", "border_terrier"),
    183: ("Dog", "Kerry Blue Terrier", "kerry_blue"),
    184: ("Dog", "Irish Terrier", "irish_terrier"),
    185: ("Dog", "Norfolk Terrier", "norfolk_terrier"),
    186: ("Dog", "Norwich Terrier", "norwich_terrier"),
    187: ("Dog", "Yorkshire Terrier", "yorkshire_terrier"),
    188: ("Dog", "Wire-Haired Fox Terrier", "fox_terrier"),
    189: ("Dog", "Lakeland Terrier", "lakeland_terrier"),
    190: ("Dog", "Sealyham Terrier", "sealyham"),
    191: ("Dog", "Airedale Terrier", "airedale"),
    192: ("Dog", "Cairn Terrier", "cairn"),
    193: ("Dog", "Australian Terrier", "australian_terrier"),
    194: ("Dog", "Dandie Dinmont Terrier", "dandie_dinmont"),
    195: ("Dog", "Boston Bull / Boston Terrier", "boston_terrier"),
    196: ("Dog", "Miniature Schnauzer", "schnauzer"),
    197: ("Dog", "Giant Schnauzer", "giant_schnauzer"),
    198: ("Dog", "Standard Schnauzer", "standard_schnauzer"),
    199: ("Dog", "Scotch Terrier", "scottish_terrier"),
    200: ("Dog", "Tibetan Terrier", "tibetan_terrier"),
    201: ("Dog", "Silky Terrier", "silky_terrier"),
    202: ("Dog", "Soft-Coated Wheaten Terrier", "wheaten_terrier"),
    203: ("Dog", "West Highland White Terrier", "westie"),
    204: ("Dog", "Lhasa Apso", "lhasa_apso"),
    205: ("Dog", "Flat-Coated Retriever", "flat_coated_retriever"),
    206: ("Dog", "Curly-Coated Retriever", "curly_coated_retriever"),
    207: ("Dog", "Golden Retriever", "golden_retriever"),
    208: ("Dog", "Labrador Retriever", "labrador_retriever"),
    209: ("Dog", "Chesapeake Bay Retriever", "chesapeake_bay_retriever"),
    210: ("Dog", "German Short-Haired Pointer", "pointer"),
    211: ("Dog", "Vizsla", "vizsla"),
    212: ("Dog", "English Setter", "english_setter"),
    213: ("Dog", "Irish Setter", "irish_setter"),
    214: ("Dog", "Gordon Setter", "gordon_setter"),
    215: ("Dog", "Brittany Spaniel", "brittany"),
    216: ("Dog", "Clumber Spaniel", "clumber"),
    217: ("Dog", "English Springer Spaniel", "springer_spaniel"),
    218: ("Dog", "Welsh Springer Spaniel", "springer_spaniel"),
    219: ("Dog", "Cocker Spaniel", "cocker_spaniel"),
    220: ("Dog", "Sussex Spaniel", "sussex_spaniel"),
    221: ("Dog", "Irish Water Spaniel", "water_spaniel"),
    222: ("Dog", "Kuvasz", "kuvasz"),
    223: ("Dog", "Schipperke", "schipperke"),
    224: ("Dog", "Groenendael", "groenendael"),
    225: ("Dog", "Malinois", "malinois"),
    226: ("Dog", "Briard", "briard"),
    227: ("Dog", "Australian Kelpie", "kelpie"),
    228: ("Dog", "Komondor", "komondor"),
    229: ("Dog", "Old English Sheepdog", "old_english_sheepdog"),
    230: ("Dog", "Shetland Sheepdog", "sheltie"),
    231: ("Dog", "Collie", "collie"),
    232: ("Dog", "Border Collie", "border_collie"),
    233: ("Dog", "Bouvier des Flandres", "bouvier"),
    234: ("Dog", "Rottweiler", "rottweiler"),
    235: ("Dog", "German Shepherd", "german_shepherd"),
    236: ("Dog", "Doberman Pinscher", "doberman_pinscher"),
    237: ("Dog", "Miniature Pinscher", "miniature_pinscher"),
    238: ("Dog", "Greater Swiss Mountain Dog", "swiss_mountain_dog"),
    239: ("Dog", "Bernese Mountain Dog", "bernese_mountain_dog"),
    240: ("Dog", "Appenzeller", "appenzeller"),
    241: ("Dog", "EntleBucher", "entlebucher"),
    242: ("Dog", "Boxer", "boxer"),
    243: ("Dog", "Bullmastiff", "bullmastiff"),
    244: ("Dog", "Tibetan Mastiff", "tibetan_mastiff"),
    245: ("Dog", "French Bulldog", "french_bulldog"),
    246: ("Dog", "Great Dane", "great_dane"),
    247: ("Dog", "Saint Bernard", "saint_bernard"),
    248: ("Dog", "Eskimo Dog", "eskimo_dog"),
    249: ("Dog", "Alaskan Malamute", "malamute"),
    250: ("Dog", "Siberian Husky", "siberian_husky"),
    251: ("Dog", "Dalmatian", "dalmatian"),
    252: ("Dog", "Affenpinscher", "affenpinscher"),
    253: ("Dog", "Basenji", "basenji"),
    254: ("Dog", "Pug", "pug"),
    255: ("Dog", "Leonberger", "leonberger"),
    256: ("Dog", "Newfoundland", "newfoundland"),
    257: ("Dog", "Great Pyrenees", "great_pyrenees"),
    258: ("Dog", "Samoyed", "samoyed"),
    259: ("Dog", "Pomeranian", "pomeranian"),
    260: ("Dog", "Chow Chow", "chow_chow"),
    261: ("Dog", "Keeshond", "keeshond"),
    262: ("Dog", "Brabancon Griffon", "griffon"),
    263: ("Dog", "Pembroke Welsh Corgi", "corgi"),
    264: ("Dog", "Cardigan Welsh Corgi", "corgi"),
    265: ("Dog", "Toy Poodle", "poodle"),
    266: ("Dog", "Miniature Poodle", "poodle"),
    267: ("Dog", "Standard Poodle", "poodle"),
    268: ("Dog", "Mexican Hairless / Xoloitzcuintli", "xolo"),

    # ------------------ CATS (281 - 285) ------------------
    281: ("Cat", "Tabby / Domestic Cat", "indie_cat"),
    282: ("Cat", "Bengal / Tiger Cat", "bengal"),
    283: ("Cat", "Persian Cat", "persian"),
    284: ("Cat", "Siamese Cat", "siamese"),
    285: ("Cat", "Egyptian Mau / Shorthair", "british_shorthair"),
}
